### ISSUE TITLE
ERROR - Reference update function failed prematurely. Review immediately

### ISSUE THREAD

**Issue by patrikgrenfeldt** [Clinical-Genomics/microSALT#106]
**Describe the bug**
Cronic detected failure for the command:
/home/proj/production/servers/resources/hasta.scilifelab.se/crontabs/microsalt-start.sh

ERROR - Reference update function failed prematurely. Review immediately
Traceback (most recent call last):
  File "/home/proj/bin/conda/envs/P_microSALT/bin/microSALT", line 8, in <module>
    sys.exit(root())
  File "/home/proj/bin/conda/envs/P_microSALT/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/proj/bin/conda/envs/P_microSALT/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/proj/bin/conda/envs/P_microSALT/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/proj/bin/conda/envs/P_microSALT/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/proj/bin/conda/envs/P_microSALT/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/proj/bin/conda/envs/P_microSALT/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/proj/bin/conda/envs/P_microSALT/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/proj/bin/conda/envs/P_microSALT/lib/python3.6/site-packages/microSALT/cli.py", line 396, in autobatch
    ext_refs.update_refs()
  File "/home/proj/bin/conda/envs/P_microSALT/lib/python3.6/site-packages/microSALT/utils/referencer.py", line 83, in update_refs
    self.fetch_external(self.force)
  File "/home/proj/bin/conda/envs/P_microSALT/lib/python3.6/site-packages/microSALT/utils/referencer.py", line 160, in fetch_external
    profile_no = re.search(r"\d+", sample[2]).group(0)
AttributeError: 'NoneType' object has no attribute 'group'

RESULT CODE: 1

**To Reproduce**
My guess on Steps to reproduce the behavior:
1. Become hiseq.clinical
2. Bash /home/proj/production/servers/resources/hasta.scilifelab.se/crontabs/microsalt-start.sh

**Expected behavior**
No errors, all waiting microbial projects should have been started

**Screenshots**

**Software version (please complete the following information):**

**Additional context**

**Comment by sylvinite** [comment]
Issue due to pubMLST changing the text on their website.
Code revised and pushed to production.
